### ISSUE TITLE
[Doubt] rbenv 

### ISSUE THREAD

**Issue by leonardofl** [PoliGNU/sitedeploy#22]
Humm... I did not get the rbenv thing.
I understood that it lets us standardize the Ruby version, so every person that works on the project will use the same Ruby version.
I installed rvenv and ruby-build, but I did not understand how to use the right Ruby version. Would it be somewhere in the repo?

**Comment by diraol** [comment]
Take a look at the Readme, I Think I've written there.

Diego Rabatone Oliveira

Em 26 de dez de 2016 7:34 PM, "Leonardo Leite" <notifications@github.com>
escreveu:

Humm... I did not get the rbenv thing.
I understood that it lets us standardize the Ruby version, so every person
that works on the project will use the same Ruby version.
I installed rvenv and ruby-build, but I did not understand how to use the
right Ruby version. Would it be somewhere in the repo?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/PoliGNU/sitedeploy/issues/22>, or mute the thread

**Comment by leonardofl** [comment]
Ha, found it! Tks!

**Comment by leonardofl** [comment]
Ops, not really...
The doc says `As an example here, let's install Ruby version 2.3.3`. Well, I installed even Ruby 2.4.0.
But if I run ruby -v on terminal, I got 2.3.0, which was already installed on my machine.
So I still miss the specification of which ruby version we must use.
I would expect to be somewhere like the Gemfile or the Rakefile... (I do not know Ruby hehe)

**Comment by diraol** [comment]
As stated on the Readme, the command below would choose the Ruby version to
be used.

rbenv global 2.3.3

**Comment by leonardofl** [comment]
$ rbenv global 2.4.0
    $ rbenv version
    2.4.0 (set by /home/leonardo/.rbenv/version)

Looks OK, but...

    $ ruby -v
    ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
    $ irb
    2.3.0 :001 > 

Looks like rbenv did not work.

**Comment by diraol** [comment]
Have you executed these commands:

    $ echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
    $ echo 'eval "$(rbenv init -)"' >> ~/.bashrc
    $ source ~/.bashrc

?? (They force the rbenv path to be evaluated prior to the system installed ruby, if any)

**Comment by leonardofl** [comment]
Yeah!!! Now it worked... I got confused because it was a kind of mixed with the install process, and I installed it in another way (Arch packages ;)
I'll try let the readme more concise and assertive...

But, why ruby 2.3.0? The latest version is 2.4.0. Let's use 2.4.0?

**Comment by diraol** [comment]
No problem going with 2.4.0 if everything works there [It was released just
two days ago].

**Comment by leonardofl** [comment]
Uah!!! I'll make a test here...

**Comment by leonardofl** [comment]
I got some warning issues with ruby 2.4.0. So lets keep 2.3.3 ;)
